### ISSUE TITLE
 Can I use cpu to test?

### ISSUE THREAD

**Issue by JinMengKang** [ljsabc/MangaLineExtraction#2]

**Comment by ljsabc** [comment]
Of course. But according to my experiences you may need tens of second to
process one single image.

ljsabc

**Comment by JinMengKang** [comment]
And I also occur some problems,Is it my version of the environment?
python-->3.6.2  tensorflow-->1.4.0

Traceback (most recent call last):
  File "/home/tf_envs/anaconda3/envs/tf3.6/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/home/tf_envs/anaconda3/envs/tf3.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 3 and 24 for 'Assign_4' (op: 'Assign') with input shapes: [3,3,1,24], [24,1,3,3].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_mse.py", line 85, in <module>
    test(sys.argv[1])
  File "test_mse.py", line 51, in test
    model = loadModel(home)
  File "test_mse.py", line 46, in loadModel
    model.load_weights("./erika_unstable.h5")
  File "/home/tf_envs/anaconda3/envs/tf3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 2701, in load_weights
    self.load_weights_from_hdf5_group(f)
  File "/home/tf_envs/anaconda3/envs/tf3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 2787, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/tf_envs/anaconda3/envs/tf3.6/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1544, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/home/tf_envs/anaconda3/envs/tf3.6/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 573, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/home/tf_envs/anaconda3/envs/tf3.6/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 276, in assign
    validate_shape=validate_shape)
  File "/home/tf_envs/anaconda3/envs/tf3.6/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 57, in assign
    use_locking=use_locking, name=name)
  File "/home/tf_envs/anaconda3/envs/tf3.6/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/tf_envs/anaconda3/envs/tf3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "/home/tf_envs/anaconda3/envs/tf3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/tf_envs/anaconda3/envs/tf3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/tf_envs/anaconda3/envs/tf3.6/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/tf_envs/anaconda3/envs/tf3.6/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 0 in both shapes must be equal, but are 3 and 24 for 'Assign_4' (op: 'Assign') with input shapes: [3,3,1,24], [24,1,3,3].

**Comment by ljsabc** [comment]
Please refer to #1 .
